[build]
  # Build the Lovable UI located in the doc-sight-search-main subfolder
  command = "npm ci && npm --prefix doc-sight-search-main ci && npm --prefix doc-sight-search-main run build && npx prisma migrate deploy && npx prisma generate"
  publish = "doc-sight-search-main/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200